### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by sashimacs** [konrad1977/welcome-dashboard#2]
Pulling in the package with use-package+elpaca results in:
```
⛔ Error (use-package): welcome/:catch: Cannot open load file: No such file or directory, async
```

I think because `async` (https://github.com/jwiegley/emacs-async ?) is not declared as a dependency in your `Package-Requires`.

**Comment by konrad1977** [comment]
I think it was a mistake to have (require 'async) at the top. I am not using it. Removed it now. Check if it works for you?

**Comment by sashimacs** [comment]
Fixed 👍
