### ISSUE TITLE
There is an error when recentf-list is nil

### ISSUE THREAD

**Issue by sooriravindra** [konrad1977/welcome-dashboard#3]
The following line breaks when recentf-list is nil

https://github.com/konrad1977/welcome-dashboard/blob/030cb5e5888d3f02e04a80d70adc4f29486bc6fa/welcome.el#L246

I believe there needs to be a check for nil and a mention in the README that the recentf-mode should be on

**Comment by konrad1977** [comment]
Yes it does. Try the latest version now. Just fixed it. Thanks for reporting.
Fixed in https://github.com/konrad1977/welcome-dashboard/commit/752eb14201f114db7bba41a9eeeb1cb438a97709

**Comment by sooriravindra** [comment]
Thanks for the fix. Verified.
