### ISSUE TITLE
Add option to disable weather info

### ISSUE THREAD

**Issue by arkhan** [konrad1977/welcome-dashboard#4]
Hello, great job with this.

option can be added to disable weather section?

![image](https://user-images.githubusercontent.com/3141865/236860640-ac3ddf66-2426-46c2-96ff-1e6986ca5587.png)

Thanks

**Comment by konrad1977** [comment]
Thanks for the suggestion. Fixed in https://github.com/konrad1977/welcome-dashboard/commit/82cc3931797f4b0508c294edd2c5b88a5547b46c

**Comment by arkhan** [comment]
thanks

**Comment by konrad1977** [comment]
I think the error message (not the correct design) you got is because you never added longitude and latitude to you config. It might be better to check that you have something filled in for those settings rather than a boolean maybe?

**Comment by arkhan** [comment]
> I think the error message (not the correct design) you got is because you never added longitude and latitude to you config. It might be better to check that you have something filled in for those settings rather than a boolean maybe?

Yes, I think it's a better solution

**Comment by konrad1977** [comment]
This is now done in the latest version.
I removed the previous variable and only checks if latitude and longitude is set.

**Comment by arkhan** [comment]
> This is now done in the latest version. I removed the previous variable and only checks if latitude and longitude is set.

Great, thanks!
