### ISSUE TITLE
Add support to straight.el

### ISSUE THREAD

**Issue by arkhan** [konrad1977/welcome-dashboard#5]
Hello, Great job.

Support can be added to view packages loaded with straight.

![image](https://user-images.githubusercontent.com/3141865/236861159-bbcccaf6-78da-4cd6-9a4e-e438064c9a30.png)

Thanks

**Comment by konrad1977** [comment]
I added check for straight in this commit: https://github.com/konrad1977/welcome-dashboard/commit/031e08815981afb072de4847c352c6d75bb31d6d

But please check the latest version. I don't use straight so you need to confirm that it works or not.

**Comment by arkhan** [comment]
> I added check for straight in this commit: [031e088](https://github.com/konrad1977/welcome-dashboard/commit/031e08815981afb072de4847c352c6d75bb31d6d)
> 
> But please check the latest version. I don't use straight so you need to confirm that it works or not.

I just proved the latest version, but the number of packages installed still does not appear

I leave the [el-fetch](https://gitlab.com/xgqt/emacs-el-fetch/-/blob/0142f58f075ea39aa6cc7ed35dd599afc4b6b450/src/el-fetch/el-fetch.el#L197) solution as a reference

**Comment by konrad1977** [comment]
Hopefully fixed in this version: https://github.com/konrad1977/welcome-dashboard/commit/191837904498e213c9367ed3847fd020dec2cefa
Thanks.

**Comment by konrad1977** [comment]
@arkhan can I close this issue?

**Comment by arkhan** [comment]
> @arkhan can I close this issue?

Yes, great work.

![image](https://github.com/konrad1977/welcome-dashboard/assets/3141865/a9631e43-62c8-4e4f-abf5-a9ef7af1596b)

Thanks
