### ISSUE TITLE
Add support for nerd-icons

### ISSUE THREAD

**Issue by XDream8** [konrad1977/welcome-dashboard#6]
[nerd-icons](https://github.com/rainstormstudio/nerd-icons.el) is an alternative to all-the-icons.

**Comment by konrad1977** [comment]
Done: https://github.com/konrad1977/welcome-dashboard/commit/f8ad2f3754f26705aceabaea1f1bab3249028cb0

**Comment by konrad1977** [comment]
`(setq  welcome-dashboard-use-nerd-icons t)`

**Comment by XDream8** [comment]
Good job, thanks
